name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  goreleaser:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CENSYS_ARTIFACT_RELEASER_APP_ID }}
          private-key: ${{ secrets.CENSYS_ARTIFACT_RELEASER_PRIVATE_KEY }}
          repositories: |
            cencli
            homebrew-tap

      - uses: actions/setup-go@v5
        id: go
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Restore Go build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-gobuild-${{ steps.go.outputs.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gobuild-${{ steps.go.outputs.go-version }}-
      - name: Restore GOBIN (tool) cache
        uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-gobin-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-gobin-
      - name: Generate completions
        run: make completions
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
